💚 Fix publishing and dry-run (#1978)
https://github.com/cfug/dio/actions/runs/6269363038/job/17025684902

```console
Run [[ dart pub publish --dry-run  ]] in dio
Error: Package validation found the following potential issue:
* Rename the top-level "docs" directory to "doc".
  The Pub layout convention is to use singular directory names.
  Plural names won't be correctly identified by Pub and other tools.
  See https://dart.dev/tools/pub/package-layout.
Package validation found the following hint:
* The declared SDK constraint is '>=2.15.0 <3.0.0', this is interpreted as '>=2.15.0 <4.0.0'.
  
  Consider updating the SDK constraint to:
  
  environment:
    sdk: '>=2.15.0 <4.0.0'
  

Package has 1 warning and 1 hint.
```

### New Pull Request Checklist

- [x] I have read the
[Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the
[project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid
conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm
adding
- [ ] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

Our dry-run workflows are not running functionally.